# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='node_id',
        ),
    ]
