# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_nodes_node_code'),
        ('domains', '0002_remove_domains_node_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='node_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nodes.nodes'),
        ),
    ]
